### ISSUE TITLE
Add more search engines 

### ISSUE THREAD

**Issue by codeviking** [allenai/santiago#22]
We have a list of search engines now on the home page. We should add more:

* http://covidseer.ist.psu.edu/search
* https://www.covidscholar.com/
* https://covid-search.doctorevidence.com/

**Comment by skohlmeier** [comment]
Added one more.

**Comment by kyleclo** [comment]
https://discourse.cord-19.semanticscholar.org/t/cord-19-available-on-ludwig-guru/124
https://covid19.ludwig.guru/

**Comment by kyleclo** [comment]
https://discourse.cord-19.semanticscholar.org/t/cord-full-text-papers-searchable-in-covid-19-cognitive-city/116
 https://covid-19.cognitive.city

**Comment by lindawagner** [comment]
https://covid19.ludwig.guru/
LIA COVID-19 (Ludwig Initiative Against COVID-19)

Background FWIW: My name is Antonio Rotolo and I am the CEO and Co-Founder of Ludwig. An Italy-based startup working in the NLP space. We're the creators of ludwig.guru, a sentence search engine for better English writing. 
We wanted to thank you for this spectacular initiative and decided to join your efforts and put our technology at the service of the community. Being Italy at the war front, we feel particularly emotionally involved in this.
We created LIA COVID-19 (Ludwig Initiative Against COVID-19), freely accessible at covid19.ludwig.guru, by coupling the CORD-19 database with our search algorithm. Our goal is to help medical doctors, immunologists, virologists, biologists and researchers find articles with ease and surgical precision.

**Comment by lindawagner** [comment]
https://discourse.cord-19.semanticscholar.org/t/deepmine-literature-mining-from-cord-19-dataset/108

**Comment by codeviking** [comment]
We should also just link to this:
https://discourse.cord-19.semanticscholar.org/t/cord-19-demos-and-resources/132
